# Generated by Django 3.0.2 on 2020-01-14 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('env', models.CharField(default='SOME STRING', max_length=15)),
                ('version', models.CharField(default='SOME STRING', max_length=50)),
                ('build', models.CharField(default='SOME STRING', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
