# Generated by Django 3.0.2 on 2020-01-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appdata',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
